### ISSUE TITLE
Provide an option for returning paths rather than values

### ISSUE THREAD

**Issue by danielaparker** [psumiya/json-path-web#1]
https://sumiya.page/jpath.html should provide an option for returning paths rather than values, see

[PATH_LIST configuration](https://github.com/json-path/JsonPath#path-vs-value)

**Comment by psumiya** [comment]
@danielaparker Should be available now.
 
<img width="1155" alt="Jpath_AS_PATH_LIST" src="https://user-images.githubusercontent.com/14323747/225815669-8abb36cd-bd55-418c-a0ff-1d5d1385400b.png">

**Comment by danielaparker** [comment]
Indeed it it. Thanks!
