### ISSUE TITLE
The page should mention the name and version of the JSONPath implementation 

### ISSUE THREAD

**Issue by danielaparker** [psumiya/json-path-web#2]
JSONPath had its beginnings in 2007 as a short article by Stefan Goessner, since then, there have been many implementations that have interpreted that article differently, see [JSONPath Comparisons](https://cburgmer.github.io/json-path-comparison/). Since implementations don't behave the same, you should specify the name and version of the one you are supporting, I know it's Jayway JSONPath, but someone else coming across your site may not. I would also suggest including a link back to the Jayway site, https://github.com/json-path/JsonPath.

**Comment by psumiya** [comment]
Updated now to show the Jayway Json path reference at the top of the page.

For posterity, this page went live nearly couple of months ago, on Jan 15: https://hachyderm.io/@sumiya/109695179751925377
